# Generated by Django 3.1.7 on 2021-03-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='note_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=150, unique=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('note_text', models.CharField(max_length=20000)),
            ],
        ),
    ]
