# Generated by Django 3.1.7 on 2021-03-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=150, unique=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('text', models.CharField(max_length=20000)),
            ],
        ),
    ]
