# Generated by Django 3.1.7 on 2021-03-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0004_auto_20210303_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note_model',
            name='category',
            field=models.CharField(max_length=264),
        ),
    ]
