# Generated by Django 3.1.6 on 2021-03-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0005_auto_20210303_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=264)),
                ('username', models.CharField(max_length=264, unique=True)),
                ('gender', models.CharField(max_length=264, unique=True)),
                ('age', models.CharField(max_length=264, unique=True)),
            ],
        ),
    ]
