# Generated by Django 3.1.6 on 2021-03-07 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0007_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Note_model',
        ),
    ]
