# Generated by Django 3.1.7 on 2021-03-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0009_userprofileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.TextField(max_length=248)),
                ('class_number', models.TextField(max_length=248)),
                ('class_status', models.TextField(max_length=100)),
            ],
        ),
    ]
